# Generated by Django 5.0.14 on 2026-07-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('quote', 'Request a Quote'), ('project', 'Start Your Project'), ('appointment', 'Book Appointment'), ('talk', "Let's Talk")], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('lab_interest', models.CharField(choices=[('design', 'Design Lab'), ('code', 'Code Lab'), ('ai', 'AI Lab'), ('platform', 'Msafi Platform'), ('unsure', 'Not sure yet')], default='unsure', max_length=20)),
                ('budget_range', models.CharField(blank=True, max_length=60)),
                ('preferred_contact', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone', 'Phone call')], default='whatsapp', max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_handled', models.BooleanField(default=False, help_text="Tick once you've responded to this lead.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
