# Generated by Django 5.0.14 on 2026-07-16 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('lab', models.CharField(choices=[('design', 'Design Lab'), ('code', 'Code Lab'), ('ai', 'AI Lab'), ('platform', 'Msafi Platform')], max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('summary', models.CharField(help_text='One-liner shown on cards/grids.', max_length=300)),
                ('description', models.TextField(help_text='Full case-study body. Markdown or plain text.')),
                ('cover_image', models.ImageField(upload_to='portfolio/covers/')),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated, e.g. React, Django, PostgreSQL', max_length=300)),
                ('live_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage highlights.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
